# Generated by Django 5.1.7 on 2025-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0003_questionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
